spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

# 쿼리 파라미터 로그 확인용
logging:
  level:
    org.hibernate.type: trace

# 커스텀 yml 설정값
club:
  query-param:
    offset-name: "page"
    offset-size: 0
    limit-name: "size"
    limit-size: 10